### ISSUE TITLE
[Sample Issue] Failed to create VirtualMachineScalesetextension with exception Value cannot be null. (Parameter 'id')

### ISSUE THREAD

**Issue by v-bafa** [Azure/azure-rest-api-specs-examples#1921]
### Link to sample

https://github.com/Azure/azure-rest-api-specs-examples/blob/e5d9625122924e4f53a94c8037b5b915a682054b/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2022-03-01/examples-dotnet/virtualMachineScaleSetExamples/VirtualMachineScaleSetExtensions_CreateOrUpdate_MinimumSet_Gen.cs

### Library name and version

Azure.ResourceManager.Compute 1.0.1

### Language of the Sample

- [X] C#/.NET
- [ ] Java
- [ ] JavaScript/TypedScript
- [ ] Python
- [ ] Golang
- [ ] Other - Please specify in Issue details field

### Sample Issue Type

- [X] Sample not working
- [ ] Sample missing
- [ ] Do not understand sample

### Issue details

Exception:
Value cannot be null. (Parameter 'id')

   at Azure.ResourceManager.ArmResource..ctor(ArmClient client, ResourceIdentifier id)
   at Azure.ResourceManager.Compute.VirtualMachineScaleSetExtensionResource..ctor(ArmClient client, ResourceIdentifier id)
   at Azure.ResourceManager.Compute.VirtualMachineScaleSetExtensionOperationSource.Azure.Core.IOperationSource<Azure.ResourceManager.Compute.VirtualMachineScaleSetExtensionResource>.CreateResult(Response response, CancellationToken cancellationToken)
   at Azure.Core.NextLinkOperationImplementation.OperationToOperationOfT`1.<UpdateStateAsync>d__3.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Core.OperationInternal`1.<UpdateStatusAsync>d__20.MoveNext()
   at Azure.Core.OperationPoller.<WaitForCompletionAsync>d__11.MoveNext()
   at Azure.Core.OperationInternalBase.<WaitForCompletionResponseAsync>d__19.MoveNext()
   at Azure.Core.OperationInternal`1.<WaitForCompletionAsync>d__19.MoveNext()
   at Azure.ResourceManager.Compute.VirtualMachineScaleSetExtensionCollection.CreateOrUpdate(WaitUntil waitUntil, String vmssExtensionName, VirtualMachineScaleSetExtensionData data, CancellationToken cancellationToken)
   at ASCRemediatorFunction.Remediations.VmssRemediations.InstallLogAnalyticsAgentExtensionOnWindows(ArmClient armClient, OmsWorkSpaceProperties ascWorkSpace, String resourceId, ILogger log) in C:\Data\SourceCode\AzDO\ASCAutomation\ASCRemediatorFunction\Remediations\VmssRemediations.cs:line 49

### Expected behavior

The extension should be created successfully.

### Actual behavior

Failed to create extension with exception.

### Reproduction Steps

VirtualMachineScaleSetExtensionData vmssExtensionData = new VirtualMachineScaleSetExtensionData("ExtensionName");
ArmOperation<VirtualMachineScaleSetExtensionResource> vmssExtensionResource = ssExtensionCollection.CreateOrUpdate(Azure.WaitUntil.Completed, vmssExtensionData.Name, vmssExtensionData);

### Environment

.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.102\

Host:
  Version:      7.0.2
  Architecture: x64
  Commit:       d037e070eb

.NET SDKs installed:
  6.0.308 [C:\Program Files\dotnet\sdk]
  7.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

IDE: Visual Studio 2022

**Comment by xboxeer** [comment]
closed due to duplicated with this one https://github.com/Azure/azure-sdk-for-net/issues/33992
