### ISSUE TITLE
policyStates.summarizeForManagementGroup

### ISSUE THREAD

**Issue by fernandohonig** [Azure/azure-rest-api-specs-examples#3367]
### Library name and version

https://learn.microsoft.com/es-es/rest/api/policy/policy-states/summarize-for-management-group?tabs=JavaScript#code-try-0

### Language of the Sample

- [ ] C#/.NET
- [ ] Java
- [X] JavaScript/TypedScript
- [ ] Python
- [ ] Golang
- [ ] Other - Please specify in Issue details field

### Sample Issue Type

- [X] Sample not working
- [ ] Sample missing
- [ ] Do not understand sample

### Issue details

When executing this piece of code, it throws: 
- "Cannot use 'in' operator to search for 'queryOptions' in myManagementGroup"

### Expected behavior

Return this:

```
{
  "@odata.context": "https://management.azure.com/providers/Microsoft.Management/managementGroups/myManagementGroup/providers/Microsoft.PolicyInsights/policyStates/$metadata#summary",
  "@odata.count": 1,
  "value": [
    {
      "@odata.id": null,
      "@odata.context": "https://management.azure.com/providers/Microsoft.Management/managementGroups/myManagementGroup/providers/Microsoft.PolicyInsights/policyStates/$metadata#summary/$entity",
      "results": {
        "queryResultsUri": "https://management.azure.com/providers/Microsoft.Management/managementGroups/myManagementGroup/providers/Microsoft.PolicyInsights/policyStates/latest/queryResults?api-version=2019-10-01&$from=2019-10-05 18:00:00Z&$to=2019-10-06 18:00:00Z&$filter=(PolicyDefinitionAction eq 'deny' or PolicyDefinitionAction eq 'audit') and IsCompliant eq false",
        "nonCompliantResources": 15410,
        "nonCompliantPolicies": 68,
        "resourceDetails": [
          {
            "complianceState": "compliant",
            "count": 1400
          },
          {
            "complianceState": "noncompliant",
            "count": 15410
          }
        ],
        "policyDetails": [
          {
            "complianceState": "noncompliant",
            "count": 68
          }
        ],
        "policyGroupDetails": [
          {
            "complianceState": "noncompliant",
            "count": 14
          }
        ]
      },
      "policyAssignments": []
    }
  ]
}
```

### Actual behavior

Using my own management group name, with and without options, same result.

```
  "trace": [
    "TypeError: Cannot use 'in' operator to search for 'queryOptions' in stz",
    "    at getPropertyFromParameterPath (/opt/nodejs/node_modules/@azure/core-client/dist/index.js:1144:41)",
    "    at getOperationArgumentValueFromParameter (/opt/nodejs/node_modules/@azure/core-client/dist/index.js:1103:44)",
    "    at calculateQueryParameters (/opt/nodejs/node_modules/@azure/core-client/dist/index.js:1719:39)",
    "    at getRequestUrl (/opt/nodejs/node_modules/@azure/core-client/dist/index.js:1647:45)",
    "    at PolicyInsightsClient.sendOperationRequest (/opt/nodejs/node_modules/@azure/core-client/dist/index.js:1902:21)",
    "    at PolicyStatesImpl.summarizeForManagementGroup (/opt/nodejs/node_modules/@azure/arm-policyinsights/dist/index.js:6411:28)",
    "    at Runtime.exports.handler (/var/task/index.js:27:44)",
    "    at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1147:29)"
  ]
```

### Reproduction Steps

Try to run the provided code sample.

**Comment by MaryGao** [comment]
Thanks for reporting and I will take a look at this issue!

**Comment by kazrael2119** [comment]
@fernandohonig could you share your code and the package version for me?

**Comment by kazrael2119** [comment]
I tried to test the sample response, it works. 
could you install @azure/logger and add below code at the top of your code?
```
import { setLogLevel } from "@azure/logger";

 setLogLevel("verbose");
```

we want to get your log to trace this issue, thanks

**Comment by kazrael2119** [comment]
close this issue as there has been no response for a long time. please create a new issue if necessary. Thanks
