### ISSUE TITLE
[Sample Issue] azure.core.exceptions.HttpResponseError: (CannotSetProperty) Cannot set or update property sourceVmId. for DTL custom_images.begin_create_or_update()

### ISSUE THREAD

**Issue by ggorge-etiqa** [Azure/azure-rest-api-specs-examples#5133]
### Link to sample

https://learn.microsoft.com/en-us/rest/api/dtl/custom-images/create-or-update?view=rest-dtl-2018-09-15&tabs=Python

### Library name and version

azure-mgmt-devtestlabs 9.0.0

### Language of the Sample

- [ ] C#/.NET
- [ ] Java
- [ ] JavaScript/TypedScript
- [x] Python
- [ ] Golang
- [ ] Other - Please specify in Issue details field

### Sample Issue Type

- [x] Sample not working
- [ ] Sample missing
- [ ] Do not understand sample

### Issue details

```
Traceback (most recent call last):
  File "C:\tools\script\_common\create-dtl-custom-image-from-vm.py", line 103, in <module>
    create_image(
  File "C:\tools\script\_common\create-dtl-custom-image-from-vm.py", line 42, in create_image
    response = client.custom_images.begin_create_or_update(
  File "C:\Users\isac\AppData\Roaming\Python\Python39\site-packages\azure\mgmt\devtestlabs\operations\_custom_images_operations.py", line 311, in begin_create_or_update
    raw_result = self._create_or_update_initial(
  File "C:\Users\isac\AppData\Roaming\Python\Python39\site-packages\azure\mgmt\devtestlabs\operations\_custom_images_operations.py", line 260, in _create_or_update_initial
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (CannotSetProperty) Cannot set or update property sourceVmId.
Code: CannotSetProperty
Message: Cannot set or update property sourceVmId.
```

### Environment

Python 3.9.13

**Comment by ggorge-etiqa** [comment]
It seems that the error is thrown when you try to create/update an existing custom image from a different VM.
